#!/bin/sh

newUrl=`wp option get siteurl`
if [ $? -ne 0 ]; then
	echo
    echo "Could not detect site url.  Are you inside a wordpress directory?"
    exit
fi

hostname=`hostname`
serverPrefix=${hostname::${#hostname}-1}
environment=${hostname: -1}

if [ $environment == 'p' ]; then
	echo "You should not run this script in a production environment."
	exit
fi

sourceServer=$serverPrefix'p'

dumpFilename=`ssh -q $sourceServer "PATH=/usr/bin/mysqldump:$PATH wp --path=/app001/www/tin db export --porcelain"`
ssh -q $sourceServer gzip $dumpFilename
scp -q $sourceServer:$dumpFilename.gz /tmp
ssh -q $sourceServer "rm $dumpFilename.gz"

gunzip /tmp/$dumpFilename.gz
change-wordpress-url-in-database /tmp/$dumpFilename $newUrl /tmp/$dumpFilename.local
rm /tmp/$dumpFilename

wp db import /tmp/$dumpFilename.local
rm /tmp/$dumpFilename.local

# Sync files
rsync -a --delete -e "ssh -q" $sourceServer:`pwd`/wp-content/uploads/ wp-content/uploads/
rsync -a --delete -e "ssh -q" $sourceServer:`pwd`/wp-content/plugins/ wp-content/plugins/
